language: "python"
sudo: required
dist: xenial
addons:
  chrome: stable
  apt:
    packages:
      - build-essential
python:
  - "3.7"
cache:
  apt: true
  pip: true
  directories:
    - ./node_modules
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm i -g greenkeeper-lockfile@1
before_script:
  - npm install
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload
before_deploy:
  - "echo ${TRAVIS_TAG}"
  - "node bin/repver.js ${TRAVIS_TAG} > package.json.new"
  - "mv package.json.new package.json"
deploy:
  - provider: "npm"
    email: hiroaki@hysoftware.net
    skip_cleanup: true
    api_key:
      secure: >-
        Mab65jpUfCklfFsTo2s7FEGbQ9NuD7Exmn0gDyd4/K08rWHWiCg/s7cyz5bHInqiYRURbx
        J3Jb8bSoxVBH/PHwOHPQuchu3arHiT+rFaHITfxrLp8lY24BvitRd9EYTpdzeHVymazQFx
        EGjvf8sYt/hwyYmNPzJ53rLQ6d2v/72SWl52fM8VyJExLjBLae/CmXgZd/W03YdZH22a2C
        5JpIxtEv5QkpYjwYvWLoWG9Zulozz6ss1qNBA2xzH8mz9DhZQccUOl4PL1kNooln+KcS7i
        P5j25GvIoOafzgxPDrW2lXBAYvgeNqpforhF9JuyOoBGLPHY4ZesjK5T56mXjUKMGmdpCV
        xVUuD2twdhUYxnjkv40qloiX8nQolzO/WoYrWQkuBKOPEVLyXXbppsPM4z+Vmidr4PSOTn
        UKMo4NOynwVqUa31BVvoIqxS2Jx/XuI1VY1UxkN7TT1w0edJdyIFseoHpPpdxziL6gMlnY
        EP4NVNEUuEsB4lsthvBC/tKS25HOQ9PhMOX4z9G/aTHxFvmEmDFuzL7Z9tAtkxzU89lYxu
        jcmUefFVa5hzg9B0dTKxHiFpe7wh+G/eF0Vh+pDZUxYLlZygrD8b8RBxHVHZhaoNas1a1r
        qX1dNHk+qIkMS1Ww7/yEFcHnI1oPKD9qWV1QChwssQ3JegBwnpgXk=
    on:
      tags: true
