language: "python"
sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - build-essential
python:
  - "python"
cache:
  apt: true
  directories:
    - ./venv
    - ./node_modules
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm i -g greenkeeper-lockfile@1
before_script:
  - npm install
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload
before_deploy:
  - "echo ${TRAVIS_TAG}"
  - "node bin/repver.js ${TRAVIS_TAG} > package.json.new"
  - "mv package.json.new package.json"
deploy:
  - provider: "npm"
    email: hiroaki@hysoftware.net
    skip_cleanup: true
    api_key:
      secure: >-
        DYA0cbLerw45E2aRfIL1NZT7d3T8WzHd1dEqf4Ne17J3J1kqe/eY6RlPFAfWalFRbHP3lF
        MZzi7SxJKUvBxeSi+V0uHYwB50DMlOUKNc0T+lhbfh/N76w51qIL+MxG8CPYUmLsq2KQFs
        e/Je6KwHXPkPAFN2aIxv2fqbMPxc+/VG/SlVRAFzIMBKIyO6Z/hLw/BkmKAqFm9ufboFBF
        suqM/0f1Bk03p69z/8ewXHeMjFt/LcAxkd3t8mEitJTDVnCbII6czFpvjQPCNqLKxdqzzM
        jNDMBq4DM8IROHpVuN2Fcdg3mVbfxR2CduVmkvr+hw+fVfppt2UxGPpfOyZ3dTavakVlHu
        1bN0GvOFvYXlR1GykLp8/IVLFmJ8hZPmiIofm1OLm8JGTqPwWfQxpYQEq/eVsK+uRjTG1d
        D+koSaosMmGs8rlHtnvKRx2skWWMPAyqympEFYfnlyQeo951IiAF0MB63KRO6sVJpM55I8
        WhD/nWynuovx4vy5b4o9oytN3cGOPzrLlyY1JoF3G8x4XZsHjc9T04D1xuPDEqBIc5G77a
        ImgwLXgJT4cI/5+ei7xWaW7zjwdVDe4yhlaK1JEpi+3/TGwyp+OTZRYUdazMHvNKxW9oko
        6eekE5KAScGhfZT72ePWz2hMy3eAvsUqb30s0/KUyixp22esVWfyQ=
    on:
      tags: true
