language: "node_js"
node_js:
  - "5"
deploy:
  - provider: "npm"
    api_key: "YOUR_API_KEY"
    email: hiroaki@hysoftware.net
    skip_cleanup: true
    api_key:
      secure: "bXtRraye9Dpw0UjtBSSn1rBjQ8OkNI189SPaS+g3DJQm/DWDJCe/Oki/eV4XbkA42OcJ3jtLVfGnkvAm9z+0c+QJZucvGqvVF/5kiEoVRsHgCHCB+jVcUwMFsWq7v8yeACNKPEXMPYfRJhquk/AvqLR0CR5ts6AReCuGlE/MoiIP1XEifjyqlmcYGPQGew+qrRJ83hUVYhy80K0U44x6QPoPP8kstymMl/RXS7OeTG3k8iDWKUvzAl0o8zjXduAF9jA7OnPHQAyFrNU1XdDTSZov2LFU4Zt0uMMol2z4JhzdV6g3W+Xp6Epb1uFSQqrU1RTZ1J1aVMefIq30ArophgfHAQae2LRjjl5xpRm29tUOWrW1R2+lZSC4lFOJsgqvD0kUF3vMuvaVUIxXdo5QAj2h18K58w1cd0LeLG5YDKPNIt6vWx4UxqRitginhPisRCSL2vF3P1TJf9sLBwq0oDXXPru6lP8Ey93yxdnISFikiwmdfjj+d3/UwVu5ck8YtgCOOWAl5rsYnppJnwq8QvBW3n1BRvIgmgDaixtM9Kco4qI4/5x/7rBc8X8Q0R5iOe3+aQCnVotM9mbHfxAJem4nFQr6ilE3FFwlhhfw9STR/sh2coObXmflMlukf+0dNY/r3oGNmcZcf+k+TY3qMQ9bQpbdTOPC/PwS+iu7P6g="
    on:
      tags: true
