module.exports =
  "coffee": require "./coffee"
  "js": require "./js"
  "karma": require "./karma"
  "less": require "./less"
  "protractor": require "./protractor"
  "python": require "./python"
  "sass": require "./sass"
  "selfcheck": require "./selfcheck"
  "server": require "./server"
  "helper": require "./helper"
